# GNU Make solution makefile autogenerated by Premake

ifndef config
  config=debug_keksframework
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_keksframework)
  KeksNL_config = debug_keksframework
  HeaderParser_config = debug_keksframework
endif
ifeq ($(config),release_keksframework)
  KeksNL_config = release_keksframework
  HeaderParser_config = release_keksframework
endif

PROJECTS := KeksNL HeaderParser

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

KeksNL:
ifneq (,$(KeksNL_config))
	@echo "==== Building KeksNL ($(KeksNL_config)) ===="
	@${MAKE} --no-print-directory -C . -f KeksNL.make config=$(KeksNL_config)
endif

HeaderParser:
ifneq (,$(HeaderParser_config))
	@echo "==== Building HeaderParser ($(HeaderParser_config)) ===="
	@${MAKE} --no-print-directory -C HeaderParser -f Makefile config=$(HeaderParser_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f KeksNL.make clean
	@${MAKE} --no-print-directory -C HeaderParser -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_keksframework"
	@echo "  release_keksframework"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   KeksNL"
	@echo "   HeaderParser"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
